In [15]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

In [2]:
data = pd.read_csv('covid_19_clean_complete.csv')

In [3]:
data.shape

(49068, 10)

In [4]:
data.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [9]:
data['Date'] = pd.to_datetime(data['Date'])
data.dtypes

Province/State            object
Country/Region            object
Lat                      float64
Long                     float64
Date              datetime64[ns]
Confirmed                  int64
Deaths                     int64
Recovered                  int64
Active                     int64
WHO Region                object
dtype: object

In [44]:
data['Year'] = pd.DatetimeIndex(data['Date']).year

In [11]:
data['Country/Region'].value_counts()

China             6204
Canada            2256
France            2068
United Kingdom    2068
Australia         1504
                  ...
Holy See           188
Honduras           188
Hungary            188
Iceland            188
Lesotho            188
Name: Country/Region, Length: 187, dtype: int64

In [12]:
data['WHO Region'].value_counts()

Europe                   15040
Western Pacific          10340
Africa                    9024
Americas                  8648
Eastern Mediterranean     4136
South-East Asia           1880
Name: WHO Region, dtype: int64

### Exploring Cases Each WHO Region

In [60]:
region_wise_confirmed = data.groupby('WHO Region')[['Confirmed', 'Deaths', 'Recovered']].sum()
region_wise_confirmed

                       Confirmed    Deaths  Recovered
WHO Region
Africa                  21791827    439978   11193730
Americas               402261194  19359292  157069444
Eastern Mediterranean   74082892   1924029   48050703
Europe                 248879793  19271040  123202075
South-East Asia         55118365   1458134   30030327
Western Pacific         26374411    932430   18861950

In [63]:
barchart = px.bar(
    data_frame = region_wise_confirmed, x = region_wise_confirmed.index , y = 'Confirmed',               
    opacity = 0.9, orientation = "v", barmode = 'relative',          
    hover_data = ['Deaths', 'Recovered'],
    color_continuous_scale=px.colors.diverging.Picnic,      
    range_color=[1,10000], 
    labels={"y":"Total Confirmed Cases"}, title='WHO Region-wise Total Cases',
    template='gridon'

)


pio.show(barchart)

Americas and Europe had the most cases in 2020.

### Top 15 Countries with Most Active Cases

In [66]:
most_active = data.groupby('Country/Region')['Active'].sum().sort_values(ascending = False).iloc[:15]
most_active

Country/Region
US                156981121
Brazil             31094060
United Kingdom     22624595
Russia             19668578
India              15987913
France             10980287
Spain               9277432
Canada              8656985
Peru                7748957
Italy               7363518
Pakistan            5633262
South Africa        5150341
Bangladesh          4924394
Netherlands         4528235
Sweden              4524247
Name: Active, dtype: int64

In [72]:
pie_chart = px.pie(
                data_frame = most_active, values=most_active.values, names = most_active.index,
                labels = {"state":"the State"},       
                title = 'Top 15 Countries with the Most Active Cases',     
                template = 'presentation',            
                width = 800, height = 600, hole = 0.2,                           
                )

pio.show(pie_chart)

### Distribution Country and WHO Region Wise

In [83]:
pd.set_option('display.max_rows', None)

df1 = data.groupby(['WHO Region', "Country/Region"])['Confirmed', 'Deaths', 'Recovered'].sum().sort_values(ascending = False,by = ['Confirmed', 'Deaths', 'Recovered'])
df1

C:\Users\wajiz.pk\AppData\Local\Temp\ipykernel_744\2098695563.py:3: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

                                                        Confirmed    Deaths  \
WHO Region            Country/Region
Americas              US                                224345948  11011411
                      Brazil                             89524967   3938034
Europe                Russia                             45408411    619385
South-East Asia       India                              40883464   1111831
Europe                Spain                              27404045   3033030
                      United Kingdom                     26748587   3997775
                      Italy                              26745145   3707717
                      France                             21210926   3048524
                      Germany                            21059152    871322
Eastern Mediterranean Iran                               19339267   1024136
Americas              Peru                               19263916    652113
Europe                Turkey                             17903345    466056
Americas              Chile                              16935654    322480
                      Mexico                             14946202   1728277
Western Pacific       China                              14132002    672413
Eastern Mediterranean Pakistan                           12833994    264729
                      Saudi Arabia                       12362961    105150
Africa                South Africa                       11168743    181979
Americas              Canada                              9356551    699566
South-East Asia       Bangladesh                          8754729    115633
Americas              Colombia                            6893122    236525
Eastern Mediterranean Qatar                               6377607      7123
Europe                Belgium                             6281116    963679
                      Netherlands                         5167516    622314
                      Sweden                              4973160    448913
Americas              Ecuador                             4678496    346618
                      Argentina                           4450658     97749
Europe                Belarus                             4426759     28391
Eastern Mediterranean Egypt                               4142819    186936
South-East Asia       Indonesia                           4057909    220272
Europe                Portugal                            3855363    146603
                      Switzerland                         3696604    207858
Eastern Mediterranean United Arab Emirates                3658838     25387
Western Pacific       Singapore                           3502472      2441
Europe                Ukraine                             3214085     85248
Eastern Mediterranean Kuwait                              3120160     23084
                      Iraq                                3093628    121392
Western Pacific       Philippines                         2972611    110892
Europe                Poland                              2755525    118018
                      Israel                              2677930     31627
                      Ireland                             2571918    161948
Eastern Mediterranean Oman                                2559773     11804
Americas              Dominican Republic                  2495433     61786
Europe                Kazakhstan                          2430707     14621
Americas              Panama                              2378126     51756
Europe                Romania                             2363132    140031
Americas              Bolivia                             2170351     78032
Europe                Austria                             2034986     71390
Western Pacific       Japan                               1952495     85559
Eastern Mediterranean Afghanistan                         1936390     49098
                      Bahrain                             1755206      5115
Western Pacific       South Korea                         1647537     33518
Africa                Nigeria                             1634040     39416
Europe                Armenia                             1587173     27089
                      Serbia                              1376322     28876
                      Denmark                             1305978     60602
Americas              Guatemala                           1273708     49133
Africa                Ghana                               1246644      6908
Americas              Honduras                            1228583     37941
Africa                Algeria                             1179755     77972
Europe                Moldova                             1156957     38196
                      Czechia                             1146758     33364
                      Azerbaijan                          1134717     14282
                      Norway                              1008821     25664
Eastern Mediterranean Morocco                             1002746     23170
Western Pacific       Australia                            960247     11387
                      Malaysia                             876874     12971
Africa                Cameroon                             844817     22354
Europe                Finland                              713167     30338
South-East Asia       Nepal                                682623      1660
Europe                Uzbekistan                           678008      2938
Africa                Cote d'Ivoire                        611062      4717
Europe                Kyrgyzstan                           596200     14979
Eastern Mediterranean Sudan                                586392     35415
Europe                Luxembourg                           501355     11624
Africa                Senegal                              467457      7177
                      Kenya                                464603     10463
Americas              El Salvador                          453036     11429
Europe                North Macedonia                      440483     21235
Africa                Congo (Kinshasa)                     427604     10888
Americas              Venezuela                            412231      4101
Europe                Bulgaria                             410722     17654
Africa                Guinea                               403605      2356
Europe                Bosnia and Herzegovina               396634     16373
                      Hungary                              396247     51053
                      Tajikistan                           383026      3915
South-East Asia       Thailand                             366527      6289
Europe                Greece                               362615     19215
Africa                Ethiopia                             357928      5887
Americas              Costa Rica                           347151      2037
Eastern Mediterranean Djibouti                             336216      3011
Americas              Haiti                                333181      6663
Africa                Gabon                                330678      2497
Europe                Croatia                              299218     10372
Eastern Mediterranean West Bank and Gaza                   233461      1370
Europe                Kosovo                               225972      5229
                      Iceland                              221241      1141
Africa                Mauritania                           219095      6720
Europe                Estonia                              216505      6826
Americas              Cuba                                 216346      8145
Africa                Madagascar                           207296      1699
Eastern Mediterranean Somalia                              206646      7006
Africa                Central African Republic             198659      2010
Europe                Albania                              196702      5708
                      Lithuania                            188762      7019
                      Slovenia                             186132     11326
                      Slovakia                             176429      2692
Western Pacific       New Zealand                          175979      2181
South-East Asia       Maldives                             173602       705
                      Sri Lanka                            166865      1105
Eastern Mediterranean Lebanon                              166607      3520
Americas              Paraguay                             156373      1663
Africa                Equatorial Guinea                    153258      2246
                      Mali                                 151494      8229
Americas              Nicaragua                            137545      4867
Africa                Zambia                               129421      2643
Eastern Mediterranean Tunisia                              126590      5250
Africa                Guinea-Bissau                        122994      1291
                      South Sudan                          118818      2006
Europe                Latvia                               118383      2458
                      Cyprus                               107176      1962
Africa                Niger                                102223      5948
                      Congo (Brazzaville)                  101609      2696
                      Burkina Faso                          96153      5583
                      Sierra Leone                          95846      4186
Americas              Uruguay                               94742      2456
Europe                Andorra                               94404      5423
Eastern Mediterranean Jordan                                93144      1041
Africa                Malawi                                89666      1640
Europe                Georgia                               85213      1266
Africa                Cabo Verde                            82732       854
Europe                San Marino                            74949      5086
                      Montenegro                            72422      1379
Africa                Rwanda                                71242       169
Europe                Malta                                 67483       765
Eastern Mediterranean Yemen                                 67180     17707
Africa                Benin                                 64406      1095
                      Chad                                  64226      5523
                      Eswatini                              63160       763
Eastern Mediterranean Libya                                 62321      1612
Americas              Jamaica                               61392      1005
Africa                Mozambique                            58006       361
                      Uganda                                56688         6
Western Pacific       Taiwan*                               55593       840
Africa                Liberia                               51775      3341
                      Zimbabwe                              50794       881
                      Tanzania                              49327      1985
                      Togo                                  47390      1295
                      Sao Tome and Principe                 46884       950
Western Pacific       Vietnam                               40675         0
Africa                Mauritius                             39448      1161
Americas              Suriname                              32247       721
Africa                Namibia                               28836        72
South-East Asia       Burma                                 25188       639
Africa                Angola                                22662      1078
Eastern Mediterranean Syria                                 20946       973
Americas              Guyana                                19089      1346
Western Pacific       Brunei                                18168       226
                      Cambodia                              17079         0
                      Mongolia                              16999         0
Africa                Comoros                               15823       337
                      Botswana                              15306       120
Americas              Trinidad and Tobago                   14967       949
                      Bahamas                               12100      1203
Europe                Monaco                                11993       425
Africa                Eritrea                               11786         0
                      Burundi                               11351       106
Americas              Barbados                              10652       738
Europe                Liechtenstein                         10351       116
Africa                Lesotho                                6794        98
South-East Asia       Bhutan                                 4971         0
Africa                Gambia                                 4845       209
Americas              Antigua and Barbuda                    4487       326
Africa                Seychelles                             3977         0
Americas              Saint Vincent and the Grenadines       2771         0
                      Belize                                 2636       222
South-East Asia       Timor-Leste                            2487         0
Americas              Grenada                                2466         0
Western Pacific       Fiji                                   2266         0
Americas              Saint Lucia                            2236         0
Western Pacific       Laos                                   2229         0
Americas              Dominica                               2059         0
                      Saint Kitts and Nevis                  1772         0
Europe                Greenland                              1507         0
                      Holy See                               1356         0
Western Pacific       Papua New Guinea                       1185         2
Africa                Western Sahara                          901        63

                                                        Recovered
WHO Region            Country/Region
Americas              US                                 56353416
                      Brazil                             54492873
Europe                Russia                             25120448
South-East Asia       India                              23783720
Europe                Spain                              15093583
                      United Kingdom                       126217
                      Italy                              15673910
                      France                              7182115
                      Germany                            17107839
Eastern Mediterranean Iran                               15200895
Americas              Peru                               10862846
Europe                Turkey                             13345389
Americas              Chile                              13292593
                      Mexico                             11141225
Western Pacific       China                              11466866
Eastern Mediterranean Pakistan                            6936003
                      Saudi Arabia                        8474107
Africa                South Africa                        5836423
Americas              Canada                                    0
South-East Asia       Bangladesh                          3714702
Americas              Colombia                            2823811
Eastern Mediterranean Qatar                               4676443
Europe                Belgium                             1627492
                      Netherlands                           16967
                      Sweden                                    0
Americas              Ecuador                             1772210
                      Argentina                           1680024
Europe                Belarus                             2771925
Eastern Mediterranean Egypt                               1197283
South-East Asia       Indonesia                           1677484
Europe                Portugal                            1809966
                      Switzerland                         2957883
Eastern Mediterranean United Arab Emirates                2402874
Western Pacific       Singapore                           2372884
Europe                Ukraine                             1387463
Eastern Mediterranean Kuwait                              2205347
                      Iraq                                1790961
Western Pacific       Philippines                          785042
Europe                Poland                              1465856
                      Israel                              1521162
                      Ireland                             1997530
Eastern Mediterranean Oman                                1439269
Americas              Dominican Republic                  1211513
Europe                Kazakhstan                          1342402
Americas              Panama                              1213644
Europe                Romania                             1409409
Americas              Bolivia                              571653
Europe                Austria                             1638380
Western Pacific       Japan                               1307911
Eastern Mediterranean Afghanistan                          798240
                      Bahrain                             1334787
Western Pacific       South Korea                         1246797
Africa                Nigeria                              600928
Europe                Armenia                              857482
                      Serbia                               735730
                      Denmark                             1057021
Americas              Guatemala                            416757
Africa                Ghana                                814529
Americas              Honduras                             135380
Africa                Algeria                              755897
Europe                Moldova                              652369
                      Czechia                              651140
                      Azerbaijan                           703402
                      Norway                               544430
Eastern Mediterranean Morocco                              703960
Western Pacific       Australia                            711928
                      Malaysia                             703056
Africa                Cameroon                             588941
Europe                Finland                              544492
South-East Asia       Nepal                                308056
Europe                Uzbekistan                           423777
Africa                Cote d'Ivoire                        309368
Europe                Kyrgyzstan                           301587
Eastern Mediterranean Sudan                                240835
Europe                Luxembourg                           379664
Africa                Senegal                              286778
                      Kenya                                161998
Americas              El Salvador                          240972
Europe                North Macedonia                      214483
Africa                Congo (Kinshasa)                     135073
Americas              Venezuela                            151542
Europe                Bulgaria                             182621
Africa                Guinea                               276575
Europe                Bosnia and Herzegovina               207156